#!/usr/bin/env python3
"""Build a credential-free iPhone Calendar-to-CSV Shortcut for monthly review.

Only bundled Apple actions are used. Eastern month boundaries are embedded as
offset-aware dates, so travelling with a phone does not change the export month.
Validate and sign the resulting XML with Shortcuts Playground before delivery.
"""
from __future__ import annotations

import argparse
import json
import plistlib
from datetime import datetime, timedelta
from pathlib import Path
from uuid import uuid4
from zoneinfo import ZoneInfo

NAME = "Jordana Monthly Calendar Export"
COLUMNS = ["Month", "Exported At", "Calendar", "Title", "Start", "End", "Duration Minutes", "All Day"]
USER_PROMPT = "i alos want to create a new shortcut that we can out on jordanas phone .. it pull sher clendar at end of month and makes a csv of all her appointments onher calendat.. excliinmg all day evens and then we can male a report for that as well .. so tht way enbed of month jrodna can compare the two for her mauik review"


def ref(name: str) -> dict:
    return {"Type": "Variable", "VariableName": name}


def token(name: str) -> dict:
    return {"Value": ref(name), "WFSerializationType": "WFTextTokenAttachment"}


def template(*parts: str | dict) -> dict:
    value, attachments = "", {}
    for part in parts:
        if isinstance(part, str):
            value += part
        else:
            offset = len(value.encode("utf-16-le")) // 2
            attachments[f"{{{offset}, 1}}"] = part
            value += "\ufffc"
    return {"Value": {"string": value, "attachmentsByRange": attachments}, "WFSerializationType": "WFTextTokenString"}


def month_bounds() -> dict:
    zone = ZoneInfo("America/New_York")
    bounds = {}
    for year in range(2000, 2100):
        for month in range(1, 13):
            start = datetime(year, month, 1, tzinfo=zone)
            following = datetime(year + (month == 12), month % 12 + 1, 1, tzinfo=zone)
            bounds[start.strftime("%Y-%m")] = {"Start": start.isoformat(), "End": (following - timedelta(seconds=1)).isoformat()}
    return bounds


def build_shortcut() -> dict:
    actions = []

    def add(identifier, **parameters):
        parameters.setdefault("UUID", str(uuid4()).upper())
        action = {"WFWorkflowActionIdentifier": "is.workflow.actions." + identifier, "WFWorkflowActionParameters": parameters}
        actions.append(action)
        return parameters["UUID"]

    def comment(value):
        add("comment", WFCommentActionText=value)

    def save(name, action_id, output_name):
        add("setvariable", WFVariableName=name, WFInput={"Value": {"Type": "ActionOutput", "OutputUUID": action_id, "OutputName": output_name}, "WFSerializationType": "WFTextTokenAttachment"})

    def date_format(source, name, pattern):
        action_id = add("format.date", WFDate=template(ref(source)), WFDateFormatStyle="Custom", WFDateFormat="Custom", WFDateFormatString=pattern, WFLocale="en_US")
        save(name, action_id, "Formatted Date")

    comment("Export every timed appointment across all calendars for the selected Eastern calendar month. All-day events are excluded. Save a dated CSV and share it to the Mac for comparison in Reports. Calendar titles and times are preserved; notes, locations and credentials are not exported. Month selection supports 2000–2099.")
    comment("Shortcuts generated by Shortcuts Playground. May contain mistakes. Always check the shortcut's actions first.\n\nThis shortcut was created via the following user prompt:\n\n> " + USER_PROMPT)
    comment("--- CHOOSE MONTH ---\nUse any date in the month to export. The default is last month.\nALLOW_DATETIME_FORMAT: the CSV uses ISO 8601 dates with offsets and dated filenames.")
    now = add("date", WFDateActionMode="Current Date")
    save("Export Date", now, "Date")
    previous = add("adjustdate", WFDate=template(ref("Export Date")), WFAdjustOperation="Subtract", WFDuration={"Value": {"Magnitude": 1, "Unit": "months"}, "WFSerializationType": "WFQuantityFieldValue"})
    save("Previous Month Date", previous, "Adjusted Date")
    chosen = add("ask", WFAskActionPrompt="Choose any date in the month to export", WFInputType="Date", WFAskActionDefaultAnswerDate=token("Previous Month Date"))
    save("Chosen Date", chosen, "Provided Input")
    date_format("Chosen Date", "Export Month", "yyyy-MM")
    date_format("Export Date", "Export Timestamp", "yyyy-MM-dd'T'HH:mm:ssXXXXX")
    date_format("Export Date", "File Timestamp", "yyyyMMdd-HHmmss")
    comment("--- EASTERN MONTH BOUNDARIES ---\nThis embedded date dictionary fixes month boundaries in America/New_York even when the phone is travelling. It contains date values only and needs no network service.")
    data = add("gettext", WFTextActionText=json.dumps(month_bounds(), ensure_ascii=False, separators=(",", ":")))
    decoded = add("detect.dictionary", WFInput={"Value": {"Type": "ActionOutput", "OutputUUID": data, "OutputName": "Text"}, "WFSerializationType": "WFTextTokenAttachment"})
    save("Month Boundaries", decoded, "Dictionary")
    selected = add("getvalueforkey", WFGetDictionaryValueType="Value", WFDictionaryKey=template(ref("Export Month")), WFInput=token("Month Boundaries"))
    save("Chosen Month Bounds", selected, "Dictionary Value")
    for key, name in [("Start", "Month Start"), ("End", "Month End")]:
        bound = add("getvalueforkey", WFGetDictionaryValueType="Value", WFDictionaryKey=key, WFInput=token("Chosen Month Bounds"))
        dates = add("detect.date", WFInput={"Value": {"Type": "ActionOutput", "OutputUUID": bound, "OutputName": "Dictionary Value"}, "WFSerializationType": "WFTextTokenAttachment"})
        first = add("getitemfromlist", WFItemSpecifier="First Item", WFInput={"Value": {"Type": "ActionOutput", "OutputUUID": dates, "OutputName": "Dates"}, "WFSerializationType": "WFTextTokenAttachment"})
        save(name, first, "Item from List")
    comment("--- FIND ALL TIMED EVENTS ---\nFind appointments starting inside the full month on every calendar. No calendar-name restriction and no result limit are used.")
    found = add("filter.calendarevents", WFContentItemFilter={"Value": {"WFActionParameterFilterPrefix": 1, "WFContentPredicateBoundedDate": False, "WFActionParameterFilterTemplates": [
        {"Property": "Start Date", "Operator": 1003, "Removable": True, "Values": {"Date": token("Month Start"), "AnotherDate": token("Month End")}},
        {"Property": "Is All Day", "Operator": 4, "Removable": True, "Values": {"Bool": False, "Unit": 4}},
    ]}, "WFSerializationType": "WFContentPredicateTableTemplate"}, WFContentItemSortProperty="Start Date", WFContentItemSortOrder="Oldest First", WFContentItemLimitEnabled=False)
    save("Calendar Events", found, "Calendar Events")
    count = add("count", WFInput=token("Calendar Events"), Input=token("Calendar Events"), WFCountType="Items")
    save("Event Count", count, "Count")
    header = add("gettext", WFTextActionText=",".join(COLUMNS))
    save("CSV Rows", header, "Text")
    comment("--- BUILD CSV ROWS ---\n- Repeat with Each uses Calendar Events from Find Calendar Events.\n- Repeat Item is the current appointment.\n- Double quotes are doubled and every field is quoted so commas and line breaks remain valid CSV.")
    group = str(uuid4()).upper()
    add("repeat.each", WFInput=token("Calendar Events"), GroupingIdentifier=group, WFControlFlowMode=0)
    for property_name, name in [("Title", "Event Title"), ("Calendar", "Event Calendar"), ("Start Date", "Event Start"), ("End Date", "Event End")]:
        detail = add("properties.calendarevents", WFInput=token("Repeat Item"), WFContentItemPropertyName=property_name)
        save(name, detail, property_name)
    for source, name in [("Event Title", "Quoted Title"), ("Event Calendar", "Quoted Calendar")]:
        escaped = add("text.replace", WFInput=template(ref(source)), WFReplaceTextFind='"', WFReplaceTextReplace='""', WFReplaceTextCaseSensitive=True, WFReplaceTextRegularExpression=False)
        save(name, escaped, "Updated Text")
    date_format("Event Start", "Start Timestamp", "yyyy-MM-dd'T'HH:mm:ssXXXXX")
    date_format("Event End", "End Timestamp", "yyyy-MM-dd'T'HH:mm:ssXXXXX")
    minutes = add("gettimebetweendates", WFTimeUntilFromDate=template(ref("Event Start")), WFInput=template(ref("Event End")), WFTimeUntilUnit="Minutes")
    save("Duration Minutes", minutes, "Time Between Dates")
    parts = []
    for name in ["Export Month", "Export Timestamp", "Quoted Calendar", "Quoted Title", "Start Timestamp", "End Timestamp", "Duration Minutes"]:
        if parts:
            parts.append(",")
        parts.extend(['"', ref(name), '"'])
    parts.append(',"false"')
    row = add("gettext", WFTextActionText=template(*parts))
    add("appendvariable", WFVariableName="CSV Rows", WFInput={"Value": {"Type": "ActionOutput", "OutputUUID": row, "OutputName": "Text"}, "WFSerializationType": "WFTextTokenAttachment"})
    add("repeat.each", GroupingIdentifier=group, WFControlFlowMode=2)
    comment("--- SAVE AND SHARE ---\nCombine the header and appointment rows, save a uniquely dated CSV in Files, then share that saved file to the Mac. The final message shows the exported event count.")
    combined = add("text.combine", text=token("CSV Rows"), WFTextSeparator="New Lines")
    named = add("setitemname", WFInput={"Value": {"Type": "ActionOutput", "OutputUUID": combined, "OutputName": "Combined Text"}, "WFSerializationType": "WFTextTokenAttachment"}, WFName=template("Jordana_Calendar_", ref("Export Month"), "_", ref("File Timestamp"), ".csv"))
    saved = add("documentpicker.save", WFInput={"Value": {"Type": "ActionOutput", "OutputUUID": named, "OutputName": "Renamed Item"}, "WFSerializationType": "WFTextTokenAttachment"}, WFAskWhereToSave=True, WFSaveFileOverwrite=False)
    add("share", WFInput={"Value": {"Type": "ActionOutput", "OutputUUID": saved, "OutputName": "Saved File"}, "WFSerializationType": "WFTextTokenAttachment"})
    add("showresult", Text=template("Saved ", ref("Event Count"), " timed calendar events for ", ref("Export Month"), ".\nOn the Mac, open Jordana Billing → Reports → Monthly Calendar Comparison and choose this CSV."))
    return {"WFWorkflowActions": actions, "WFWorkflowName": NAME,
            "WFWorkflowClientVersion": "2600.0.0", "WFWorkflowMinimumClientVersion": 900, "WFWorkflowMinimumClientVersionString": "900",
            "WFWorkflowIcon": {"WFWorkflowIconGlyphNumber": 59681, "WFWorkflowIconStartColor": 463140863},
            "WFWorkflowHasOutputFallback": False, "WFWorkflowImportQuestions": [], "WFWorkflowInputContentItemClasses": [],
            "WFWorkflowOutputContentItemClasses": [], "WFWorkflowTypes": []}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("output/monthly-review") / (NAME + ".xml"))
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("wb") as handle:
        plistlib.dump(build_shortcut(), handle, sort_keys=False)
    print(args.output.resolve())


if __name__ == "__main__":
    main()
